build:
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torch==2.3.0"
    - "torchaudio==2.3.0"
  run:
    - |
      git clone https://github.com/myshell-ai/MeloTTS.git /workspace/MeloTTS && \
      pip install -e /workspace/MeloTTS && \
      python3 -m unidic download && \
      echo "export PYTHONPATH=$PYTHONPATH:/workspace/MeloTTS" >> ~/.bashrc
