build:
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torch==2.3.0"
    - "torchaudio==2.3.0"
  run:
    - "pip install git+https://github.com/myshell-ai/MeloTTS.git"
    - "python3 -m unidic download"
